id: I119EE866
legacy_id: P007081
ocr_import_info:
  bdrc_scan_id: W00KG09825
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:49:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:43:51.498823+00:00'
last_modified: 2022-08-29 20:44:01.145411
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG09825
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG09825
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིས་མེད་ཆོས་འབྱུང་།
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.9684680488552924
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I00KG09867:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09867
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09867.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9684680488552924
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
