id: P007081
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:40:18.828471
source_metadata:
  id: bdr:W00KG09825
  title: རིས་མེད་ཆོས་འབྱུང་
  author: ''
  volumes:
    f73fdb9ca9054f7dae946771bbd96b54:
      image_group_id: I00KG09867
      title: Volume 1 of kong sprul ris med chos 'byung
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
