id: P007081
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09825
  title: རིས་མེད་ཆོས་འབྱུང་
  author: ''
  volumes:
    181f237207974170824c1fab26869798:
      image_group_id: I00KG09867
      title: ''
      volume_number: 1
      total_pages: 54
ebook_metadata:
  title: རིས་མེད་ཆོས་འབྱུང་
  author: ''
  sku: P007081
  cover: cover.jpg
  layers:
  - pagination
